#pragma config(Sensor, dgtl1,  led1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  led3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  led4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  led5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  led6,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  led7,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  led8,           sensorLEDtoVCC)
#pragma config(Motor,  port2,           load,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

////////////////////
// PRE AUTONOMOUS //
////////////////////
const float BAT_FULL = 8.5;
const float BAT_DEAD = 7.5;
float batAvg = 6.5;
float percentage;

task main() {
	clearTimer(T1);
	clearTimer(T2);
	//motor[load] = 127;
	while (true) {

		batAvg = ((float) nAvgBatteryLevel) * 0.001;
		percentage = (batAvg - BAT_DEAD) / (BAT_FULL - BAT_DEAD);

		if (percentage >= 1) {
			// Overcharged.
				if (time1[T1] >=  250) {
					SensorValue[led1] = !SensorValue[led1];
					clearTimer(T1);
				}
		} else if (percentage >= 0.875) {
				SensorValue[led1] = 1;
		} else {
			SensorValue[led1] = 0;
		}
		if (percentage >= 0.75) {
				SensorValue[led2] = 1;
		} else {
			SensorValue[led2] = 0;
		}
		if (percentage >= 0.625) {
				SensorValue[led3] = 1;
		} else {
			SensorValue[led3] = 0;
		}
		if (percentage >= 0.5) {
				SensorValue[led4] = 1;
		} else {
			SensorValue[led4] = 0;
		}
		if (percentage >= 0.375) {
				SensorValue[led5] = 1;
		} else {
			SensorValue[led5] = 0;
		}
		if (percentage >= 0.25) {
				SensorValue[led6] = 1;
		} else {
			SensorValue[led6] = 0;
		}
		if (percentage >= 0.125) {
				SensorValue[led7] = 1;
		} else {
			SensorValue[led7] = 0;
		}
		if (percentage > 0) {
			SensorValue[led8] = 1;
		} else if (percentage <= 0) {
				if (time1[T2] >=  250) {
					SensorValue[led8] = !SensorValue[led8];
					clearTimer(T2);
				}
		} else {
			SensorValue[led8] = 0;
		}
	}
}
